In [1]:
class Employee:
    """    class with Employee name, family, salary and department    """

    no_of_employees = 0

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(employees):
        """        function for the avg salary        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees

class FulltimeEmployee(Employee):
    """    Full Time Employee is the sub class of the Employee    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")

def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 130000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 190000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 170000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 145000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))

if __name__ == "__main__":
    main()



Few benefits as full time employee.
Average salary: 158750.0


In [2]:
import numpy as np

def replace_maxmium(array, replace_value, axis):
    """ choose from x or y depending on condition: np.where(condition, x, y) """
    output = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    print(output)

def main():

    random20 = np.random.random_sample(20) * 20 + 1

    random20_4by5 = random20.reshape((4, 5))

    replace_maxmium(random20_4by5, 0, 1)

if __name__ == "__main__":
    main()


[[ 0.          3.54893812 10.82022997 16.55099845  4.41801539]
 [ 0.          9.00850762  2.35042481 16.54001329 14.17466297]
 [ 0.          8.60584569  3.08961014  8.08239346  3.00639068]
 [ 5.20571783 18.06255224 18.79645004  0.          1.27399252]]
